name: Check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: nightly-2024-06-06
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run format check
        run: cargo fmt --all -- --check

      - name: Run clippy check
        run: cargo clippy

      - name: Run unit tests
        run: cargo test